version: '3.8'
services:
  calculator:
    image: node:14-alpine
    working_dir: /var/app/calculator-service/
    command:
      - "yarn"
      - "start"
    depends_on:
      - redis
    ports:
      - 3002:3000
    volumes:
      - .:/var/app
  rolls:
    image: node:14-alpine
    working_dir: /var/app/rolls-service/
    command:
      - "yarn"
      - "start"
    depends_on:
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
  presenter:
    image: node:14-alpine
    working_dir: /var/app/presenter-service/
    command:
      - "yarn"
      - "start"
    ports:
      - 3001:3000
    volumes:
      - .:/var/app
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
